# Generated by Django 4.1.5 on 2025-06-25 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajasAlmacenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTracking', models.CharField(max_length=200, verbose_name='numero de traking')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion de registro')),
                ('wereHouseCreated', models.BooleanField(default=False, verbose_name='werehouse creado')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCajasAlmacenadas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numeroTracking', models.CharField(max_length=200, verbose_name='numero de traking')),
                ('fecha_hora', models.DateTimeField(blank=True, editable=False, verbose_name='fecha creacion de registro')),
                ('wereHouseCreated', models.BooleanField(default=False, verbose_name='werehouse creado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cajas almacenadas',
                'verbose_name_plural': 'historical cajas almacenadass',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
