# Generated by Django 4.1.5 on 2025-07-24 15:41

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajasAlmacenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTracking', models.CharField(max_length=200, verbose_name='numero de traking')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion de registro')),
                ('wareHouseCreated', models.BooleanField(default=False, verbose_name='werehouse creado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCajasAlmacenadas',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numeroTracking', models.CharField(max_length=200, verbose_name='numero de traking')),
                ('fecha_hora', models.DateTimeField(blank=True, editable=False, verbose_name='fecha creacion de registro')),
                ('wareHouseCreated', models.BooleanField(default=False, verbose_name='werehouse creado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cajas almacenadas',
                'verbose_name_plural': 'historical cajas almacenadass',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
