# Generated by Django 4.1.5 on 2025-06-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecepcionEnPuerta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajasalmacenadas',
            old_name='wereHouseCreated',
            new_name='wareHouseCreated',
        ),
        migrations.RenameField(
            model_name='historicalcajasalmacenadas',
            old_name='wereHouseCreated',
            new_name='wareHouseCreated',
        ),
    ]
