# Generated by Django 4.1.5 on 2025-06-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepcionEnPuerta', '0002_rename_werehousecreated_cajasalmacenadas_warehousecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasalmacenadas',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='historicalcajasalmacenadas',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
