# Generated by Django 4.1.5 on 2025-07-24 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('correo_aux', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo aux')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Segundo Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('secound_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='segundo Apellido')),
                ('identificacion', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='identificacion')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('telefono_aux', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('codigo_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='codigo de cliente')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank='False', help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electrónico')),
                ('correo_aux', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='correo aux')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Segundo Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('secound_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='segundo Apellido')),
                ('identificacion', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='identificacion')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('telefono_aux', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('image', models.TextField(blank=True, max_length=255, null=True, verbose_name='Imagen de perfil')),
                ('codigo_cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='codigo de cliente')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuario',
                'verbose_name_plural': 'historical Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
