# Generated by Django 4.1.5 on 2025-07-11 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='correo_aux',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='correo aux'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='identificacion'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')]),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='telefono_aux',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='correo_aux',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo aux'),
        ),
        migrations.AddField(
            model_name='user',
            name='identificacion',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='identificacion'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_aux',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')]),
        ),
    ]
