# Generated by Django 4.1.5 on 2025-07-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_historicaluser_correo_aux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='codigo de cliente'),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='codigo de cliente'),
        ),
    ]
