# Generated by Django 4.1.5 on 2025-07-24 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('segundo_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Nombre del cliente')),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Apellido del cliente')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del cliente')),
                ('identificacion', models.CharField(max_length=150, unique=True, verbose_name='identificacion')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('correo_aux', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo aux')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('telefono_aux', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('codigo_cliente', models.CharField(max_length=200, verbose_name='codigo de cliente')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=150, verbose_name='Pais')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=150, verbose_name='Municipio')),
                ('sector', models.CharField(max_length=150, verbose_name='Sector')),
                ('casa', models.CharField(max_length=150, verbose_name='Casa')),
                ('codigo_postal', models.CharField(max_length=150, verbose_name='Codigo Postal')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClientNatural',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('segundo_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Nombre del cliente')),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Apellido del cliente')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del cliente')),
                ('identificacion', models.CharField(db_index=True, max_length=150, verbose_name='identificacion')),
                ('correo', models.EmailField(db_index=True, max_length=254, verbose_name='correo')),
                ('correo_aux', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='correo aux')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('telefono_aux', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('codigo_cliente', models.CharField(max_length=200, verbose_name='codigo de cliente')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical client natural',
                'verbose_name_plural': 'historical client naturals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDireccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pais', models.CharField(max_length=150, verbose_name='Pais')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=150, verbose_name='Municipio')),
                ('sector', models.CharField(max_length=150, verbose_name='Sector')),
                ('casa', models.CharField(max_length=150, verbose_name='Casa')),
                ('codigo_postal', models.CharField(max_length=150, verbose_name='Codigo Postal')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente_natural', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clientnatural')),
            ],
            options={
                'verbose_name': 'historical direccion',
                'verbose_name_plural': 'historical direccions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
