# Generated by Django 4.1.5 on 2025-07-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldireccion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientnatural',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientnatural',
            name='quien_envia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clientequienenvia', verbose_name='Nombre de quien env la mercancia'),
        ),
        migrations.AddField(
            model_name='historicalclientnatural',
            name='quien_recibe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clientequienrecibe', verbose_name='Nombre de quien rcb la mercancia'),
        ),
        migrations.AddField(
            model_name='historicalclienteusuariodestino',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientequienrecibe',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientequienenvia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientcourier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientcourier',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clienteusuariodestino', verbose_name='Nombre de quien env la mercancia'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente_courier', to='Client.clientcourier'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_destino', to='Client.clienteusuariodestino'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_natural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente_natural', to='Client.clientnatural'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_quien_envia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_quien_envia', to='Client.clientequienenvia'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_quien_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_quien_recibe', to='Client.clientequienrecibe'),
        ),
        migrations.AddField(
            model_name='clientnatural',
            name='quien_envia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.clientequienenvia', verbose_name='Nombre de quien env la mercancia'),
        ),
        migrations.AddField(
            model_name='clientnatural',
            name='quien_recibe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.clientequienrecibe', verbose_name='Nombre de quien rcb la mercancia'),
        ),
        migrations.AddField(
            model_name='clientcourier',
            name='usuario_destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.clienteusuariodestino', verbose_name='Nombre de quien env la mercancia'),
        ),
    ]
