# Generated by Django 4.1.5 on 2025-07-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldireccion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientnatural',
            name='Agente_relacionado',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'groups__name': 'Agente'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Agente'),
        ),
        migrations.AddField(
            model_name='historicalclientnatural',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_natural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente_natural', to='Client.clientnatural'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientnatural',
            name='Agente_relacionado',
            field=models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Agente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agente_Relacionado', to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Agente'),
        ),
    ]
