# Generated by Django 5.2.1 on 2025-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_clientcourier_is_active_clientequienenvia_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcourier',
            name='identificacion',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='clientequienenvia',
            name='identificacion',
            field=models.CharField(max_length=150, unique=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='clientequienrecibe',
            name='identificacion',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='clienteusuariodestino',
            name='identificacion',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='clientnatural',
            name='identificacion',
            field=models.CharField(max_length=150, unique=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='historicalclientcourier',
            name='identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='historicalclientequienenvia',
            name='identificacion',
            field=models.CharField(db_index=True, max_length=150, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='historicalclientequienrecibe',
            name='identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='historicalclienteusuariodestino',
            name='identificacion',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='historicalclientnatural',
            name='identificacion',
            field=models.CharField(db_index=True, max_length=150, verbose_name='identificacion'),
        ),
    ]
