# Generated by Django 4.1.5 on 2025-07-15 15:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNatural2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('segundo_nombre', models.CharField(max_length=150, verbose_name='Segundo Nombre del cliente')),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Apellido del cliente')),
                ('apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido del cliente')),
                ('identificacion', models.CharField(max_length=150, unique=True, verbose_name='identificacion')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('correo_aux', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo aux')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('telefono_aux', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('codigo_cliente', models.CharField(max_length=200, verbose_name='codigo de cliente')),
                ('is_active', models.BooleanField(default=True)),
                ('Agente_relacionado', models.OneToOneField(blank=True, limit_choices_to={'groups__name': 'Agente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agente_Relacionado', to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Agente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDireccion2',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pais', models.CharField(max_length=150, verbose_name='Pais')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=150, verbose_name='Municipio')),
                ('sector', models.CharField(max_length=150, verbose_name='Sector')),
                ('casa', models.CharField(max_length=150, verbose_name='Casa')),
                ('codigo_postal', models.CharField(max_length=150, verbose_name='Codigo Postal')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Agente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cliente_natural', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clientnatural2')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical direccion2',
                'verbose_name_plural': 'historical direccion2s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClientNatural2',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('segundo_nombre', models.CharField(max_length=150, verbose_name='Segundo Nombre del cliente')),
                ('segundo_apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Apellido del cliente')),
                ('apellido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido del cliente')),
                ('identificacion', models.CharField(db_index=True, max_length=150, verbose_name='identificacion')),
                ('correo', models.EmailField(db_index=True, max_length=254, verbose_name='correo')),
                ('correo_aux', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='correo aux')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('telefono_aux', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número telefónico válido (ej: +1234567890 o 1234567890)', regex='^\\+?[0-9\\s\\-]+$')])),
                ('codigo_cliente', models.CharField(max_length=200, verbose_name='codigo de cliente')),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Agente_relacionado', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'groups__name': 'Agente'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Agente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client natural2',
                'verbose_name_plural': 'historical client natural2s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Direccion2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=150, verbose_name='Pais')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=150, verbose_name='Municipio')),
                ('sector', models.CharField(max_length=150, verbose_name='Sector')),
                ('casa', models.CharField(max_length=150, verbose_name='Casa')),
                ('codigo_postal', models.CharField(max_length=150, verbose_name='Codigo Postal')),
                ('is_active', models.BooleanField(default=True)),
                ('Agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_Agente', to=settings.AUTH_USER_MODEL)),
                ('cliente_natural', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente_natural', to='Client.clientnatural2')),
            ],
        ),
    ]
