# Generated by Django 5.2.1 on 2025-06-11 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_clientcourier_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='cliente_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Client.clienteusuariodestino'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_quien_envia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Client.clientequienenvia'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente_quien_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Client.clientequienrecibe'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='cliente_destino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clienteusuariodestino'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='cliente_quien_envia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clientequienenvia'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='cliente_quien_recibe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Client.clientequienrecibe'),
        ),
    ]
