# Generated by Django 4.1.5 on 2025-07-15 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Client', '0004_rename_agente_historicaldireccion2_agente_or_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldireccion2',
            old_name='Agente_or_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='direccion2',
            name='Agente_or_user',
        ),
        migrations.AddField(
            model_name='direccion2',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
