# Generated by Django 4.1.5 on 2025-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_rename_agente_or_user_historicaldireccion2_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnatural2',
            name='apellido',
            field=models.CharField(max_length=150, verbose_name='Apellido del cliente'),
        ),
        migrations.AlterField(
            model_name='clientnatural2',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='historicalclientnatural2',
            name='apellido',
            field=models.CharField(max_length=150, verbose_name='Apellido del cliente'),
        ),
        migrations.AlterField(
            model_name='historicalclientnatural2',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Nombre del cliente'),
        ),
    ]
