# Generated by Django 5.2.1 on 2025-06-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_alter_direccion_cliente_courier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='cliente_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_destino', to='Client.clienteusuariodestino'),
        ),
    ]
