# Generated by Django 5.2.1 on 2025-06-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_alter_direccion_cliente_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='cliente_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente_courier', to='Client.clientcourier'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente_natural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_cliente_natural', to='Client.clientnatural'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente_quien_envia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_quien_envia', to='Client.clientequienenvia'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente_quien_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_quien_recibe', to='Client.clientequienrecibe'),
        ),
    ]
