# Generated by Django 4.1.5 on 2025-06-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_clientcourier_created_by_clientcourier_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcourier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientcourier',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='clientequienenvia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientequienenvia',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='clientequienrecibe',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientequienrecibe',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='clienteusuariodestino',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clienteusuariodestino',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='clientnatural',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientnatural',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientcourier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientcourier',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientequienenvia',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientequienenvia',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientequienrecibe',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientequienrecibe',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalclienteusuariodestino',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalclienteusuariodestino',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientnatural',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalclientnatural',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicaldireccion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaldireccion',
            name='modified_by',
        ),
    ]
